server:
  port: 4004 # Gateway listens on port 4004
#  servlet:
#    context-path: /api

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      routes:
        - id: auth-service-route
          uri: http://localhost:4005
          predicates:
            - Path=/auth/**
        - id: api-docs-auth-route
          uri: http://localhost:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://localhost:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

#         Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://localhost:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
#

auth:
  service:
    url: http://localhost:4004/auth