package com.pm.notificationservice.notification.dto;

public class EventConstants {

    public static String USER_CREATED_NOTIFICATION = "USER_CREATED_NOTIFICATION";
    public static String USER_UPDATED_NOTIFICATION = "USER_UPDATED_NOTIFICATION";
    public static String USER_ACTIVATED_NOTIFICATION = "USER_ACTIVATED_NOTIFICATION";
    public static String USER_DEACTIVATED_NOTIFICATION = "USER_DEACTIVATED_NOTIFICATION";
    public static String USER_DELETED_NOTIFICATION = "USER_DELETED_NOTIFICATION";
    public static String USER_PASSWORD_CHANGED_NOTIFICATION = "USER_PASSWORD_CHANGED_NOTIFICATION";
    public static String USER_PASSWORD_RESET_NOTIFICATION = "USER_PASSWORD_RESET_NOTIFICATION";
    public static String USER_PASSWORD_EXPIRED_NOTIFICATION = "USER_PASSWORD_EXPIRED_NOTIFICATION";
    public static String I18N_RESOURCES_EDITED="I18N_RESOURCES_EDITED";

    public static String MONTHLY_PATIENT_REPORT_JOB_COMPLETED_SUCCESS = "MONTHLY_PATIENT_REPORT_JOB_COMPLETED_SUCCESS";
    public static String MONTHLY_PATIENT_REPORT_JOB_COMPLETED_FAILED = "MONTHLY_PATIENT_REPORT_JOB_COMPLETED_FAILED";

}
