package com.pm.authservice.event;

public class EventConstants {

    public static String USER_CREATED_NOTIFICATION = "USER_CREATED_NOTIFICATION";
    public static String USER_UPDATED_NOTIFICATION = "USER_UPDATED_NOTIFICATION";
    public static String USER_ACTIVATED_NOTIFICATION = "USER_ACTIVATED_NOTIFICATION";
    public static String USER_DEACTIVATED_NOTIFICATION = "USER_DEACTIVATED_NOTIFICATION";
    public static String USER_DELETED_NOTIFICATION = "USER_DELETED_NOTIFICATION";
    public static String USER_PASSWORD_CHANGED_NOTIFICATION = "USER_PASSWORD_CHANGED_NOTIFICATION";
    public static String USER_PASSWORD_RESET_NOTIFICATION = "USER_PASSWORD_RESET_NOTIFICATION";
    public static String USER_PASSWORD_RESET_EXPIRED_NOTIFICATION = "USER_PASSWORD_RESET_EXPIRED_NOTIFICATION";

}
