spring.application.name=fts

##################
# Loggind Config  #
##################
logging.level.org.springframework.data.elasticsearch.client.WIRE=TRACE
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.apache.http=DEBUG

#############
# Actuator  #
#############
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true


##################
# Server Config  #
##################
server.port=4006
server.servlet.context-path=/fts

##################
# Elastic Search #
##################
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.scheme=http
elasticsearch.username=elastic
elasticsearch.password=changeme
document.index.pfx=
es.ca-fingerprint=